### ISSUE TITLE
Add 64bit versions

### ISSUE THREAD

**Issue by javi2ruiz** [Aevis/php_pdo_informix-1.3.1-5.6-vc11-x86#1]
Hello Aevis, I have donwload your dll but I can't load it.
I don't get any error or warning on logs. Simply, the extension doesn't load properly.

System configuration:
  - SO: Windows Server 2016 Stantard
  - Apache 2.4.37-w64-VC15
  - PHP 7.2.12-Win32-VC15-x64

After a first attemp, I have re-installed Client SDK because I had 64 bits version intalled. But I get the same result: nothing 😄 

I have tested other pdo extension and these loads well. I refer to, for example, default php 7.2 extensions pdo_odbc

As well, I have checked INFORMIXDIR is right on system environment variables.

I would appreciate any comments from you that help me find out why the library is not loaded.

Thanks.
Javi.

**Comment by Aevis** [comment]
<del>Hi Javi. All I can think of: Are you running PHP embedded in your Apache (mod_php) or through PHP-FPM (fastcgi)? The first scenario requires the Thread Safe version of the dll, the second the Non-Thread Safe. However, a mismatch should at least produce a message in your Apache error log similar to "the specific module could not be found".</del>

<del>Just to make sure, phpinfo() shows INFORMIXDIR pointing to the installation folder of the 32bit CSDK.</del>

I just realized by building your environment: You are using a 64bit Apache and PHP right? These are 32bit libraries, thus won't work. I can look into providing 64bit versions, but I don't have a 64bit compile and test environment on Windows ready right now.

**Comment by javi2ruiz** [comment]
Hi Aevis, thanks for your response.
I begin by the end: Yes INFORMIXDIR is all right phpinfo() -> INFORMIXDIR | C:\Program Files (x86)\IBM\Informix\Client-SDK

Exactly, I can see on Apache error log this lines:
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_informix' (tried: C:\\php\\ext\\pdo_informix (The specified module could not be found.), C:\\php\\ext\\php_pdo_informix.dll (%1 is not a valid Win32 application.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_informix-1.3.3-7.2-vc15-ts-x86' (tried: C:\\php\\ext\\pdo_informix-1.3.3-7.2-vc15-ts-x86 (The specified module could not be found.), C:\\php\\ext\\php_pdo_informix-1.3.3-7.2-vc15-ts-x86.dll (%1 is not a valid Win32 application.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_informix-1.3.3-7.2-vc15-nts-x86' (tried: C:\\php\\ext\\pdo_informix-1.3.3-7.2-vc15-nts-x86 (The specified module could not be found.), C:\\php\\ext\\php_pdo_informix-1.3.3-7.2-vc15-nts-x86.dll (%1 is not a valid Win32 application.)) in Unknown on line 0

As you can see I've tried everthing  😄. To load extension with diferents names too.

I read your second commentary just now. Yes, seems 64 bits is the problem.
Yesterday I downloaded VS 2017 to try compile but I have no experience to do this.

I will try:
  - Reinstall all on 32 bit (apache, php and CSDK).
  - To try to compile on 64bit, but maybe you can do this before me.

I will inform you about my progress.
Thanks.
Javi.

**Comment by Aevis** [comment]
> is not a valid Win32 application

That log entry confirms the 32/64bit version conflict. 

I'll look to add 64bit versions over the holidays. If you don't require 64bit PHP, switching to 32bit is probably the faster way.

**Comment by javi2ruiz** [comment]
> switching to 32bit is probably the faster way.

Yes, its my first option.
Thanks

**Comment by muhaizi** [comment]
Hi Aevis,

Appreciate if you could add 64bit versions for PHP 7.2 and PHP 7.3

Thanks.

**Comment by Aevis** [comment]
@javi2ruiz @muhaizi 

I finally found some time to sit down and compile new 32 and 64bit DLLs for PHP 7.2/7.3/7.4: 484215f143071793ac9822e86c4346c4e89df788
