### ISSUE TITLE
Inexact character conversion during translation

### ISSUE THREAD

**Issue by javi2ruiz** [Aevis/php_pdo_informix-1.3.1-5.6-vc11-x86#2]
Hi Silas. First of all, thanks for your work and for share this compilation.
Maybe this is not an issue really ;) but it's the right site to make a question to you.

Well, after a couple of month making tests, I have see this error on my app:
Warning: PDOStatement::fetch(): SQLSTATE[HY000]: General error: 21005 [Informix][Informix ODBC Driver]Inexact character conversion during translation. (SQLFetchScroll[21005] at ..\pecl\PDO_INFORMIX-1.3.3\informix_statement.c:1044) ISAM: 105034700

When this warning occurs, the resultset stops and doesn't get more results of the query.

I think it's just the reason because you made this custom compilation, sure?
I have tested all the possible combinations: on the connections string from PHP and on the setnet32 environment variables.

On a linux environment I have tested this sql query works right.

Any idea? 

Thanks a lot.
Javi.

**Comment by Aevis** [comment]
Hi Javi

Judging by the error message alone, it sounds like a misconfiguration of CLIENT_LOCALE and/or the DB_LOCALE on the client making the connection. Make sure that the CLIENT_LOCALE matches your Windows system locale and the DB_LOCALE your database server system locale. [Some more information from IBM](https://www-01.ibm.com/support/docview.wss?uid=swg21621347).

To delve any deeper, I'd need the query and a sample DB schema to execute it on as well as the system locales of your client and DB server. With those I can try to replicate the error.

Cheers
