### ISSUE TITLE
php 5

### ISSUE THREAD

**Issue by rakucmr** [Aevis/php_pdo_informix-1.3.1-5.6-vc11-x86#4]
will work with php 5?

**Comment by Aevis** [comment]
Hi @rakucmr. There is one .dll compiled for PHP 5.6 in the x86 folder: [php_pdo_informix-1.3.1-5.6-vc11-ts-x86.dll](https://github.com/flachglasschweiz/php_pdo_informix/blob/master/x86/php_pdo_informix-1.3.1-5.6-vc11-ts-x86.dll)

**Comment by rakucmr** [comment]
@Aevis  I'm getting this error: PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\\EasyPHP-Devserver-17\\eds-binaries\\php\\php5630vc11x86x201103150846\\ext\\php_pdo_informix.dll' - %1 is not a valid Win32 application.\r\n in Unknown on line 0;

I'm running this configuration:

- Apache: version : 2.4.25 / compiler : VC11 / architecture : x86 (32-bit)
- PHP version: 5.6.30 x86

**Comment by rakucmr** [comment]
Can you help me please I'm trying to compile it and I get this error:

C:\php-src>configure.bat --disable-all --enable-cli --with-pdo-informix="C:\Program Files\Informix Client-SDK"
Saving configure options to config.nice.bat
Checking for cl.exe ...  <in default path>
Checking for cl.exe ...  <in default path>
Detected MS compiler version 15
Detected 32-bit compiler
Checking for link.exe ...  C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN
Checking for nmake.exe ...  <in default path>
Checking for lib.exe ...  <in default path>
Checking for bison.exe ...  <in default path>
Checking for flex.exe ...  <in default path>
Checking for re2c.exe ...  <in default path>
Checking for zip.exe ...  <in default path>
Checking for lemon.exe ...  <in default path>
Checking for mc.exe ...  C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN
Checking for mt.exe ...  C:\Program Files\Microsoft SDKs\Windows\v6.0A\bin
ERROR: you chosen output directory no does not exist

I've used the steps from here https://ourcodeworld.com/articles/read/804/how-to-compile-a-php-extension-dll-file-in-windows-with-visual-studio

**Comment by Aevis** [comment]
I won't be able to test until this weekend, but it looks like you have the 64bit version of the Informix SDK installed (C:\Program Files\Informix Client-SDK). You need to install the 32bit one if you want to use the 32bit dll or compile a 32bit version yourself.

**Comment by rakucmr** [comment]
Hello, yes you are right, that was the problem, I've switched to a 32bit version and all is ok, thanks! Thanks alot!

**Comment by Aevis** [comment]
Cheers, glad it worked out.

**Comment by alvenkam** [comment]
Hi, possible to compile 64bit version for php5.6?

**Comment by Aevis** [comment]
Hi, this repo isn't maintained anymore and PHP5.6 has been eol since 2018. I'd strongly suggest to use the current 8.3 version.
