### ISSUE TITLE
pdo_informix error

### ISSUE THREAD

**Issue by Jessica28** [Aevis/php_pdo_informix-1.3.1-5.6-vc11-x86#5]
I am facing problem with PHP Informix connection. I am working with PHP 7.4.11 in Apache Server at the Server Window Server2019. Informix SDK 64 bit  (CSK4.10.FC12_Win_64) has been installed and dll (php_pdo_informix-1.3.3-7.2-vc15-ts-x64) is stored under extension folder. 

But I am seeing the error 
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_informix' (tried: C:\\xampp\\php\\ext\\pdo_informix (Das angegebene Modul wurde nicht gefunden.), C:\\xampp\\php\\ext\\php_pdo_informix.dll (Die angegebene Prozedur wurde nicht gefunden.)) in Unknown on line 0

Could someone help me with that please

**Comment by Aevis** [comment]
@Jessica28 It seems like you're using the dll for 7.2 instead of 7.4.

**Comment by Jessica28** [comment]
Thank you very much it solved.
