### ISSUE TITLE
New version 1.3.4 for PHP 8 maybe?

### ISSUE THREAD

**Issue by kisspandur** [Aevis/php_pdo_informix-1.3.1-5.6-vc11-x86#6]
Dear Aevis,

first of all, thank you for your work! It is working flawless! Awesome!
Is there any chance that you can compile the newest version (1.3.4) for 64 bit PHP 8.x?
Or if you share how to do it, I would try!
Many thanks: Zoltan

**Comment by Aevis** [comment]
Hi Zoltan

I do not have a Windows build environment ready these days, as we switched our entire development pipeline to docker a couple years back. In fact, I'll open an issue to [look for a new maintainer](https://github.com/flachglasschweiz/php_pdo_informix/issues/7).

If you want to give it a try and compile it yourself, a good starting point is: https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2. They do not mention PHP 8 and it's also missing from the [compiler overview](https://wiki.php.net/internals/windows/compiler), so maybe you'd need to use VS 2022 and/or a different SDK version.

I found this thread on [Apache Lounge](https://www.apachelounge.com/viewtopic.php?t=6359&start=0), where Jan-E posts Windows build of PHP 8 and some extensions. You could try to contact him/her if it doesn't compile with the instructions from the wiki.

**Comment by jsagrera** [comment]
Here is a x64 build for 8.1.9 using the latest 1.3.6.
[php_pdo_informix-1.3.6-8.1-vs16-ts-x64.zip](https://github.com/flachglasschweiz/php_pdo_informix/files/9401657/php_pdo_informix-1.3.6-8.1-vs16-ts-x64.zip)

**Comment by Aevis** [comment]
@jsagrera Thank you for the build!

@kisspandur Could you give this one a try? If it works, I'll add it to the repo.

**Comment by kisspandur** [comment]
You all are marvellous!
Tested on PHP v8.1.10 (x64) on Windows 10 without any problem!
(I personally don't prefer developing on Windows, I have linux servers, but that's the case now. Viva Linux!)
Many thanks again!

**Comment by joseaugustojesus** [comment]
Hello, @kisspandur , I'm trying to install informix on W10 and PHP 8.1 but I can't. Can you help me?

**Comment by kisspandur** [comment]
> Hello, @kisspandur , I'm trying to install informix on W10 and PHP 8.1 but I can't. Can you help me?

Hi! The informix database isn't on my Win10, it is installed on another machine, on a linux. I can help with that, but not with W10. Is that the real question?

**Comment by jsagrera** [comment]
If your issue is related to install the Informix server on Windows, I think it would be better if you ask in Slack (using the 'Informix' tag).  I'm sure old Informix folks would be able to help you there. ;)

**Comment by nitin-usualsmart** [comment]
Hello guys,
I have compiled the php_pdo_informix DLL for PHP-8.1.12 NTS (non-thread-safe). I hope it will be helpful. It has been tested and found to work with PHP 8.1.12 NTS, IIS 10 hosting on Windows 11 64-bit.
php_pdo_informix-1.3.6-8.1.12-vs16-nts-x64.zip
[php_pdo_informix-1.3.6-8.1.12-vs16-nts-x64.zip](https://github.com/Aevis/php_pdo_informix/files/10029625/php_pdo_informix-1.3.6-8.1.12-vs16-nts-x64.zip)
